// <auto-generated />
namespace ED_2_POO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InitialInsert : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialInsert));
        
        string IMigrationMetadata.Id
        {
            get { return "202107051128377_InitialInsert"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
